Fix deprecated implicit copy assignment operator warning
Error description:

error: definition of implicit copy assignment operator for 'Bezier<N>'
is deprecated because it has a user-provided copy